clearvars; close all;
path = '';
[samples, channels, rawData, rawTimes] = raspiImport(path);

allData = struct(...    % Organize all numerical data, 10 bit ADC, 12 bit DAC output
    'Mic1',rawData(:,1),... 
    'Mic2',rawData(:,2),...
    'Mic3',rawData(:,3),... 
    'RadarIF_I',rawData(:,4),...    % In-phase signal
    'RadarIF_Q',rawData(:,5),...    % Quadrature signal
    'DAC_Sampled',rawData(:,6),...  % DAC signal sampled back with ADC
    'DAC_Output',rawData(:,end)...    % DAC signal as requested on its output
     );
allData.RadarIF_I = allData.RadarIF_I - 512;
allData.RadarIF_Q = allData.RadarIF_Q - 512;

allTimes = struct(...   % Organize all timestamps accordingly, unit is us
    'Mic1',rawTimes(:,1),...
    'Mic2',rawTimes(:,2),...
    'Mic3',rawTimes(:,3),...
    'RadarIF_I',rawTimes(:,4),...
    'RadarIF_Q',rawTimes(:,5),...
    'DAC_Sampled',rawTimes(:,6),...
    'DAC_Output',rawTimes(:,end)...
    );
